---
title: "Adjusting the parameters of scoreGenesMat function to calculate confusion matrices for each parameter combination and dataset"
author: "BM"
date: "11/19/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(devtools)
install_github("bertamiro/Lheuristic")

library(Lheuristic) #from bertamiro @ github
library(caret)
library(purrr)
```


## Create confusion matrix for 10% L genes and 50 samples

```{r}

heurGrid1 <- expand.grid(percY1 = c(0.25, 0.33),
                        percY2 = c(0.75, 0.66),
                        aWeightMifL1 = c(-10, -25, -40),
                        aWeightMifLx = c(0, 1, 2),
                        aWeightMifL2 = c(1, 2, 4),
                        aReqPercentsMat1 = c(20, 40, 60))


heurGridx <- heurGrid1[!(heurGrid1$percY1 == "0.25" & heurGrid1$percY2 == "0.66"),] 
heurGrid <- heurGridx[!(heurGridx$percY1 == "0.33" & heurGridx$percY2 == "0.75"),]
```


```{r}
#load data
expr10x <- read.csv("~/Desktop/Selecting_GRM/A heuristic algorithm to select GRM/ParamTunning/expression10_simulTuning.csv", row.names=1)
met10x <- read.csv("~/Desktop/Selecting_GRM/A heuristic algorithm to select GRM/ParamTunning/methylation10_simulTuning.csv", row.names=1)

expr10x$Class <- as.factor(expr10x$Class)
met10x$Class <- as.factor(met10x$Class)

levels(expr10x$Class) <- c("L","NoL")
levels(met10x$Class) <- c("L","NoL") #create class factor

# 
colnames(expr10x)[51] <- "logicSc1"
colnames(met10x)[51] <- "logicSc1"

met10x_50 <- met10x
expr10x_50 <- expr10x

mets <- met10x_50
expres <- expr10x_50

scoreGenesMat <- function(mets, expres,
                          x1=percY1, x2=percY2,
                          y1=NULL, y2=NULL, percY1, percY2,
                          aReqPercentsMat1, # =standardPercentsMat,
                          aWeightMifL1,
                          aWeightMifLx,
                          aWeightMifL2)
{
  mets <- met10x_50
  expres <- expr10x_50
  N <- dim(mets)[2]
  Ngenes <-nrow(mets)
  scores <- data.frame(logicSc=rep(FALSE, Ngenes), numericSc=rep(0,Ngenes))
  rownames(scores)<- rownames(mets)
  aReqPercentsMat   <- matrix (c(10, 20, 1, 5, aReqPercentsMat1, 20, 0, 5, 10), nrow=3, byrow=TRUE)
  aWeightMifL <- matrix (c(2,-2,aWeightMifL1,1,aWeightMifLx,-2,aWeightMifL2,1,2), nrow=3, byrow=TRUE)
  aWeightMifNonL <- matrix (c(0,-2,-25,0,0,-2,0,0,0), nrow=3, byrow=TRUE)
  minmaxCounts <- toReqMat (N, aReqPercentMat=aReqPercentsMat)
  for (gene in 1:Ngenes){
    theGene <- rownames(expres)[gene]
    xVec<- mets[theGene,]
    yVec<- expres[theGene,]
    geneGrid <- calcFreqs(xMet=xVec, yExp=yVec, x1=x1, x2=x2,
                          y1=y1, y2=y2, percY1=percY1, percY2=percY2)
    # TRACE
    # if (trace) show(geneGrid)
    # TRACE
    binSc <-  binScore (geneGrid, minmaxCounts)
    scores[gene, "logicSc"] <- binSc
    numSc <- numScore (geneGrid, LShaped=binSc,
                       aWeightMifL=aWeightMifL,
                       aWeightMifNonL=aWeightMifNonL )
    scores[gene, "numericSc"] <- numSc
    scores$logicSc <- as.integer(scores$logicSc)
    scores$logicSc1 <- factor(scores$logicSc)
    levels(scores$logicSc1) <- c("NoL", "L")
  }
  return (scores)
  
}

scoresRes10x_50 <- pmap(heurGrid, scoreGenesMat) #map grid columns to function parameters
#scoresRes10x_50 <- lapply(split(heurGrid, seq(nrow(heurGrid))), scoreGenesMat)

CM10x_50 <- lapply(scoresRes10x_50, function(x) confusionMatrix(data = x$logicSc1,
                                              reference = expres$logicSc1,
                                              positive = 'L')$byClass)#confusion matrix Sensitivity, specificity, etc. With $overall we obtain kappa and accuracy, with $table we obtain CM 2x2 table
 
CMdat10x_50 <- as.data.frame(do.call(rbind, CM10x_50))#dataframe from list

paramRes10x_50 <- cbind(heurGrid, CMdat10x_50)#bind parameters' grid with resulting statistics dataframes
```


## Create confusion matrix for 1% L genes and 50 samples

```{r}
#load data
expr1x_50 <- read.csv("~/Desktop/Selecting_GRM/A heuristic algorithm to select GRM/ParamTunning/expression1_simulTuning.csv", row.names=1)
met1x_50 <- read.csv("~/Desktop/Selecting_GRM/A heuristic algorithm to select GRM/ParamTunning/methylation1_simulTuning.csv", row.names=1)

expr1x_50$Class <- as.factor(expr1x_50$Class)
met1x_50$Class <- as.factor(met1x_50$Class)

levels(expr1x_50$Class) <- c("L","NoL")
levels(met1x_50$Class) <- c("L","NoL")

# 
colnames(expr1x_50)[51] <- "logicSc1"
colnames(met1x_50)[51] <- "logicSc1"

mets <- met1x_50
expres <- expr1x_50

scoreGenesMat <- function(mets, expres,
                          x1=percY1, x2=percY2,
                          y1=NULL, y2=NULL, percY1, percY2,
                          aReqPercentsMat1, # =standardPercentsMat,
                          aWeightMifL1,
                          aWeightMifLx,
                          aWeightMifL2)
{
  mets <- met1x_50
  expres <- expr1x_50
  N <- dim(mets)[2]
  Ngenes <-nrow(mets)
  scores <- data.frame(logicSc=rep(FALSE, Ngenes), numericSc=rep(0,Ngenes))
  rownames(scores)<- rownames(mets)
  aReqPercentsMat   <- matrix (c(10, 20, 1, 5, aReqPercentsMat1, 20, 0, 5, 10), nrow=3, byrow=TRUE)
  aWeightMifL <- matrix (c(2,-2,aWeightMifL1,1,aWeightMifLx,-2,aWeightMifL2,1,2), nrow=3, byrow=TRUE)
  aWeightMifNonL <- matrix (c(0,-2,-25,0,0,-2,0,0,0), nrow=3, byrow=TRUE)
  minmaxCounts <- toReqMat (N, aReqPercentMat=aReqPercentsMat)
  for (gene in 1:Ngenes){
    theGene <- rownames(expres)[gene]
    xVec<- mets[theGene,]
    yVec<- expres[theGene,]
    geneGrid <- calcFreqs(xMet=xVec, yExp=yVec, x1=x1, x2=x2,
                          y1=y1, y2=y2, percY1=percY1, percY2=percY2)
    # TRACE
    # if (trace) show(geneGrid)
    # TRACE
    binSc <-  binScore (geneGrid, minmaxCounts)
    scores[gene, "logicSc"] <- binSc
    numSc <- numScore (geneGrid, LShaped=binSc,
                       aWeightMifL=aWeightMifL,
                       aWeightMifNonL=aWeightMifNonL )
    scores[gene, "numericSc"] <- numSc
    scores$logicSc <- as.integer(scores$logicSc)
    scores$logicSc1 <- factor(scores$logicSc)
    levels(scores$logicSc1) <- c("NoL", "L")
  }
  return (scores)
  
}

scoresRes1x_50 <- pmap(heurGrid, scoreGenesMat)
#scoresRes1x_50 <- lapply(split(heurGrid, seq(nrow(heurGrid))), scoreGenesMat)

CM1x_50 <- lapply(scoresRes1x_50, function(x) confusionMatrix(data = x$logicSc1,
                                              reference = expres$logicSc1,
                                              positive = 'L')$byClass)

CMdat1x_50 <- as.data.frame(do.call(rbind, CM1x_50))

paramRes1x_50 <- cbind(heurGrid, CMdat1x_50)
```

## Create confusion matrix for 10% L genes and 1000 samples

```{r}
#load data
expr10x_1000 <- read.csv("~/Desktop/Selecting_GRM/A heuristic algorithm to select GRM/ParamTunning/expression10_simulTuning1000.csv", row.names=1)
met10x_1000 <- read.csv("~/Desktop/Selecting_GRM/A heuristic algorithm to select GRM/ParamTunning/methylation10_simulTuning1000.csv", row.names=1)

expr10x_1000$Class <- as.factor(expr10x_1000$Class)
met10x_1000$Class <- as.factor(met10x_1000$Class)

levels(expr10x_1000$Class) <- c("L","NoL")
levels(met10x_1000$Class) <- c("L","NoL")

# 
colnames(expr10x_1000)[1001] <- "logicSc1"
colnames(met10x_1000)[1001] <- "logicSc1"

mets <- met10x_1000
expres <- expr10x_1000

scoreGenesMat <- function(mets, expres,
                          x1=percY1, x2=percY2,
                          y1=NULL, y2=NULL, percY1, percY2,
                          aReqPercentsMat1, # =standardPercentsMat,
                          aWeightMifL1,
                          aWeightMifLx,
                          aWeightMifL2)
{
  mets <- met10x_1000
  expres <- expr10x_1000
  N <- dim(mets)[2]
  Ngenes <-nrow(mets)
  scores <- data.frame(logicSc=rep(FALSE, Ngenes), numericSc=rep(0,Ngenes))
  rownames(scores)<- rownames(mets)
  aReqPercentsMat   <- matrix (c(10, 20, 1, 5, aReqPercentsMat1, 20, 0, 5, 10), nrow=3, byrow=TRUE)
  aWeightMifL <- matrix (c(2,-2,aWeightMifL1,1,aWeightMifLx,-2,aWeightMifL2,1,2), nrow=3, byrow=TRUE)
  aWeightMifNonL <- matrix (c(0,-2,-25,0,0,-2,0,0,0), nrow=3, byrow=TRUE)
  minmaxCounts <- toReqMat (N, aReqPercentMat=aReqPercentsMat)
  for (gene in 1:Ngenes){
    theGene <- rownames(expres)[gene]
    xVec<- mets[theGene,]
    yVec<- expres[theGene,]
    geneGrid <- calcFreqs(xMet=xVec, yExp=yVec, x1=x1, x2=x2,
                          y1=y1, y2=y2, percY1=percY1, percY2=percY2)
    # TRACE
    # if (trace) show(geneGrid)
    # TRACE
    binSc <-  binScore (geneGrid, minmaxCounts)
    scores[gene, "logicSc"] <- binSc
    numSc <- numScore (geneGrid, LShaped=binSc,
                       aWeightMifL=aWeightMifL,
                       aWeightMifNonL=aWeightMifNonL )
    scores[gene, "numericSc"] <- numSc
    scores$logicSc <- as.integer(scores$logicSc)
    scores$logicSc1 <- factor(scores$logicSc)
    levels(scores$logicSc1) <- c("NoL", "L")
  }
  return (scores)
  
}

scoresRes10x_1000 <-  pmap(heurGrid, scoreGenesMat)

CM10x_1000 <- lapply(scoresRes10x_1000, function(x) confusionMatrix(data = x$logicSc1,
                                              reference = expres$logicSc1,
                                              positive = 'L')$byClass)

CMdat10x_1000 <- as.data.frame(do.call(rbind, CM10x_1000))

paramRes10x_1000 <- cbind(heurGrid, CMdat10x_1000)
```


## Create confusion matrix for 1% L genes and 1000 samples

```{r}
#load data
expr1x_1000 <- read.csv("expression1_simulTuning1000.csv", row.names=1)
met1x_1000 <- read.csv("methylation1_simulTuning1000.csv", row.names=1)

expr1x_1000$Class <- as.factor(expr1x_1000$Class)
met1x_1000$Class <- as.factor(met1x_1000$Class)

levels(expr1x_1000$Class) <- c("L","NoL")
levels(met1x_1000$Class) <- c("L","NoL")

# 
colnames(expr1x_1000)[1001] <- "logicSc1"
colnames(met1x_1000)[1001] <- "logicSc1"

mets <- met1x_1000
expres <- expr1x_1000

scoreGenesMat <- function(mets, expres,
                          x1=percY1, x2=percY2,
                          y1=NULL, y2=NULL, percY1, percY2,
                          aReqPercentsMat1, # =standardPercentsMat,
                          aWeightMifL1,
                          aWeightMifLx,
                          aWeightMifL2) # , trace=FALSE)
{
  mets <- met1x_1000
  expres <- expr1x_1000
  N <- dim(mets)[2]
  Ngenes <-nrow(mets)
  scores <- data.frame(logicSc=rep(FALSE, Ngenes), numericSc=rep(0,Ngenes))
  rownames(scores)<- rownames(mets)
  aReqPercentsMat   <- matrix (c(10, 20, 1, 5, aReqPercentsMat1, 20, 0, 5, 10), nrow=3, byrow=TRUE)
  aWeightMifL <- matrix (c(2,-2,aWeightMifL1,1,aWeightMifLx,-2,aWeightMifL2,1,2), nrow=3, byrow=TRUE)
  aWeightMifNonL <- matrix (c(0,-2,-25,0,0,-2,0,0,0), nrow=3, byrow=TRUE)
  minmaxCounts <- toReqMat (N, aReqPercentMat=aReqPercentsMat)
  for (gene in 1:Ngenes){
    theGene <- rownames(expres)[gene]
    xVec<- mets[theGene,]
    yVec<- expres[theGene,]
    geneGrid <- calcFreqs(xMet=xVec, yExp=yVec, x1=x1, x2=x2,
                          y1=y1, y2=y2, percY1=percY1, percY2=percY2)
    # TRACE
    # if (trace) show(geneGrid)
    # TRACE
    binSc <-  binScore (geneGrid, minmaxCounts)
    scores[gene, "logicSc"] <- binSc
    numSc <- numScore (geneGrid, LShaped=binSc,
                       aWeightMifL=aWeightMifL,
                       aWeightMifNonL=aWeightMifNonL )
    scores[gene, "numericSc"] <- numSc
    scores$logicSc <- as.integer(scores$logicSc)
    scores$logicSc1 <- factor(scores$logicSc)
    levels(scores$logicSc1) <- c("NoL", "L")
  }
  return (scores)
  
}


scoresRes1x_1000 <-  pmap(heurGrid, scoreGenesMat)

CM1x_1000 <- lapply(scoresRes1x_1000, function(x) confusionMatrix(data = x$logicSc1,
                                              reference = expres$logicSc1,
                                              positive = 'L')$byClass)

CMdat1x_1000 <- as.data.frame(do.call(rbind, CM1x_1000))

paramRes1x_1000 <- cbind(heurGrid, CMdat1x_1000)
```


```{r}
library(xlsx)
write.xlsx(paramRes10x_50, file="paramRes_confusionmatrix.xlsx", sheetName="paramRes10x_50", row.names=FALSE)
write.xlsx(paramRes1x_50, file="paramRes_confusionmatrix.xlsx", sheetName="paramRes1x_50", append=TRUE, row.names=FALSE)
write.xlsx(paramRes10x_1000, file="paramRes_confusionmatrix.xlsx", sheetName="paramRes10x_1000", append=TRUE, row.names=FALSE)
write.xlsx(paramRes1x_1000, file="paramRes_confusionmatrix.xlsx", sheetName="paramRes1x_1000", append=TRUE, row.names=FALSE)
```


```{r}

heur_test <- data.frame(Datasets =c("set1_50","set10_50","set1_1000","set10_1000"), Sensitivity_res = c(sensitivity1, sensitivity10, sensitivity1_1000, sensitivity10_1000), Accuracy_res = c(accuracy1, accuracy10, accuracy1_1000, accuracy10_1000), Specificity_res = c(specificity1,specificity10, specificity1_1000, specificity10_1000))



kable(heur_test, escape = F, digits = 2) %>%
kable_styling(latex_options = c("striped","hold_position", "repeat_header"), font_size = 13, full_width = F) %>%
row_spec(0,background = "#94047d", color = "white")
```



## Analysis manual dels parametres (cross check)

```{r}
x1 <- 1/4
x2 <- 3/4
percY1 <- 1/4
percY2 <- 3/4 #lowest accuracy
aWeightMifL1 <- -25
aWeightMifLx <- 0
aWeightMifL2 <- 1
aReqPercentsMat1 <- 60

aWeightMifL1 <- -25 #tested -10,-40 doesn't change accuracy- combined with different percY
aWeightMifLx <- 0 #tested 1,2 doesn't change accuracy- combined with different percY
aWeightMifL2 <- 1 #tested 2,4 doesn't change accuracy- combined with different percY
aReqPercentsMat1 <- 40 #above 40 (tested up to 70 doesn't change)
sc1 <- scoreGenesMat (mets=mets, expres=expres,
                            aReqPercentsMat1=aReqPercentsMat1,
                            aWeightMifL12=aWeightMifL1,
                            aWeightMifLx=aWeightMifLx,
                            aWeightMifL2=aWeightMifL2)
c1 <- confusionMatrix(sc1[,3],mets[,51])
```

```{r}
set.seed(456)
aWeightMifL1 <- -2
aWeightMifLx <- 0
aWeightMifL2 <- 1
aReqPercentsMat1 <- 20 #lowest accuracy
sc2 <- scoreGenesMat (mets=mets, expres=expres,
                            aReqPercentsMat1=aReqPercentsMat1,
                            aWeightMifL1=aWeightMifL1,
                            aWeightMifLx=aWeightMifLx,
                            aWeightMifL2=aWeightMifL2)
c2 <- confusionMatrix(sc2[,3],mets[,51])
```

```{r}
x1 <- 1/4
x2 <- 3/4
percY1 <- 1/4
percY2 <- 3/4 #lowest accuracy
aWeightMifL1 <- -25
aWeightMifLx <- 0
aWeightMifL2 <- 1
aReqPercentsMat1 <- 60
sc3 <- scoreGenesMat (mets=mets, expres=expres,
                      aReqPercentsMat1=aReqPercentsMat1,
                      aWeightMifL1=aWeightMifL1,
                      aWeightMifLx=aWeightMifLx,
                      aWeightMifL2=aWeightMifL2,
                      x1 <- x1,
                      x2 <- x2,
                      percY1 <- percY1,
                      percY2 <- percY2)
c3 <- confusionMatrix(sc3[,3],mets[,51])
```


```{r}
x1 <- 1/4
x2 <- 3/4
percY1 <- 1/4
percY2 <- 3/4
aWeightMifL1 <- -25
aWeightMifLx <- 0
aWeightMifL2 <- 2
aReqPercentsMat1 <- 40
sc4 <- scoreGenesMat (mets=mets, expres=expres,
                      aReqPercentsMat1=aReqPercentsMat1,
                      aWeightMifL1=aWeightMifL1,
                      aWeightMifLx=aWeightMifLx,
                      aWeightMifL2=aWeightMifL2,
                      x1 <- x1,
                      x2 <- x2,
                      percY1 <- percY1,
                      percY2 <- percY2)
c4 <- confusionMatrix(sc4[,3],mets[,51])
```

```{r}
aWeightMifL1 <- -25 #no canvia res
aWeightMifLx <- 0
aWeightMifL2 <- 2 #no canvia res
aReqPercentsMat1 <- 40
sc5 <- scoreGenesMat (mets=mets, expres=expres,
                            aReqPercentsMat1=aReqPercentsMat1,
                            aWeightMifL1=aWeightMifL1,
                            aWeightMifLx=aWeightMifLx,
                            aWeightMifL2=aWeightMifL2)
c5 <- confusionMatrix(sc5[,3],mets[,51])
```

```{r}
aWeightMifL1 <- -25
aWeightMifLx <- 1
aWeightMifL2 <- 1
aReqPercentsMat1 <- 40
sc6 <- scoreGenesMat (mets=mets, expres=expres,
                            aReqPercentsMat1=aReqPercentsMat1,
                            aWeightMifL1=aWeightMifL1,
                            aWeightMifLx=aWeightMifLx,
                            aWeightMifL2=aWeightMifL2)
c6 <- confusionMatrix(sc6[,3],mets[,51])
```


```{r}
aWeightMifL1 <- -4
aWeightMifLx <- 2
aWeightMifL2 <- 1
aReqPercentsMat1 <- 40
sc7 <- scoreGenesMat (mets=mets, expres=expres,
                            aReqPercentsMat1=aReqPercentsMat1,
                            aWeightMifL1=aWeightMifL1,
                            aWeightMifLx=aWeightMifLx,
                            aWeightMifL2=aWeightMifL2)
c7 <- confusionMatrix(sc7[,3],mets[,51])
```