---
title: |
    | _A heuristic algorithm to select genes potentially regulated by methylation_
    | Esquema per l'article 
author: "Alex Sanchez-Pla"
date: "October 2019"
output:
 prettydoc::html_pretty:
    toc: true
    theme: cayman
    highlight: github
    number_sections: true
editor_options: 
  chunk_output_type: console
# bibliography: references.bib
# link-citations: yes
---

```{r setup, include=FALSE}
require(knitr)
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
                      comment = NA, prompt = TRUE, tidy = FALSE, 
                      fig.width = 7, fig.height = 7, fig_caption = TRUE,
                      cache=FALSE)
Sys.setlocale("LC_TIME", "C")
```


(_He posat els apartas que es descriuen com "For Authors" de BMC Bioinformatics:_)

# TitlePage
 El títol "A heuristic algorithm to select genes potentially regulated by methylation" està bé, Falta veure si l'hem emprat exactament igual i quansts cops, 

[_Revisar títols ja publicats per nosaltres (SLIDES, POSTERS, ALTRES ARTICLES)_]

# Abstract
Ha de tenir tres parts: __Background, Results, Conclusions__ que són les parts de l'article.

# Keywords: Methylation, L-shape, Gene regulation

# Background 
[_The Background section should explain the background to the study, its aims, a summary of the existing literature and why this study was necessary._]

## Què ha de venir aquí?

1. Una revisió sobre la __metilació__:
    + Què és
    + Com actúa
        - _No se si tocaria aquí_: Reflexió sobre què es metilen, els gens o les illes CpG o ...
        - Quina relació té amb malalties com el càncer
		
2. Perquè pot ser útil/important/interessant trobar gens regulats per metilació

3. Com s'ha abordat fins ara la cerca de gens regulats per metilació
    + Metilació diferencial [__Revisar tesi Lara!!!]__
    + Anàlisi de la correlació entre expressió i metilació
		
4. Però perquè estem aquí (quin és el context de l'article?)
    + Pot ser positiva però majoritàriament són Correlacions negatives
    + Fins i tot si la relació és lineal convé no oblidar que l’ús de “r” es bastant trist només detecta si existeix relació ( __COMPTE: NO PODRIA SER QUE AQUI AIXÒ SIGUI UN AVENTATGE?__ Al cap i a la fi si estem buscant candidats amb detectar els possibles n'hi pot haver prou.
    + Un altre tema és quan no té sentit la significació de la correlació: __Pot no haver linealitat ni monotonicitat però si L shape__

## Què tenim?
 - Backgrounds de treballs anteriors que podem adaptar per a les dues primeres parts
    - TFM Alfons
    - TFM Berta
    - Technical reports nostres
    - Articles a Mathematical abstracts
		 
## Què ens falta
Hem de veure com aborden el tema alguns articles que seleccionen gens regulats per metilació

- _Massie (2017). The importance of DNA methylation in prostate cancer development_: Analitza relacio expressio en gens de 17 estudis i fa una mena de consens agafant els que mstren canvis en més de tres dels estudis. Proporciona correlacions entre sondes més que entre gens.
- _Long et alt (2017) The Genomic Impact of DNA CpG Methylation on Gene Expression_; Relationships in Prostate Cancer. Fa algunes coses interessants q podríem tenir en compte: 
    + Considera tot el TCGA   (Potser podríem en un apèndix explorar els diferents datasets)
    + Fa referència a la idea de que els GRM són "hundreds rather tah thousands"
    + Suggereix  una forma de trobar GRM a partir de les bases de dades
- _Klett et al. (2018). ColoCare project_  amb dades d'expressio (GSE106582) i metilacio  (GSE101764) conte 194 mostres, 77 tumors i 117 de mucosa. 
    + Utilitzen random forest per la classificacio de gens, treballant amb subsets  i (a) expressio diferencial de  log2FC > 0.5 i (b) expressio diferencial de  log2FC > 0.5 i Spearman corr coef > 0.5 que millora la classificacio. 
    + Two different models, one for negatively correlated genes and one for positively correlated genes. No list of genes published.

- Alguns programes/paquets
    + Methylmix (Bioconductor)
    + PubMeth: Reviewed methylation database in cancer. http://pubmeth.biobix.be/mate/gene_cancer.html
    + Altres ?
    
### Algunes coses noves vistes a la tesi de Lara Nonell

- Parla d'una base de dades que es diu **Metylome Resource** [rnbeads.org](rnbeads.org). Potser aqui es puguin trobar gens "realment metilats"
- Associaccions no lineals: Quan la variable respostya es continua i la relacio no és lineal tenim un problema. Això ho estudia la LAra (cap. 5 i introdueix algunes idees que pootser podem estendre a altres llocs)

## Objectius

_Segurament és bona idea especificarĺos després del background_

# Results

(_This should include the findings of the study including, if appropriate, results of statistical analysis which must be included either in the text or as tables and figures_)

## Què tenim:

### Resultats relatius a mètodes

- Aqui podem presentar l'algorisme separant les dues formules
     - La binarització es L/No és L
     - l'score (S())
 - Evidentment cal descriure bé els paràmetres
      - Compte: Cal decidir si restringim que sumi 100 (i repetir-ho tot?)
 - Afegir Correlació i Venns per treure llistes d’Unió o Intersecció
 - Com s'implementa el pipeline/Algorisme
    - Seleccio de L
    - Seleccio per CoRF negativa
- Unio o Interseccio de Llistes [NO ALGORISME]
- Representar els gens sobre el genoma [NO ALGORISME

### Resultats de simulació (NOU!)

- Presentar el mètode per simular L's
- Presentar els escenaris i l'estudi de simulació
- Resultats de les simulacions 
    - Aquí resumits
    - A supplementary materials

### Aplicació a datasets reals
- El cas del Diego Arango
- TCGA?
    
### Programari per a l'anàlisi

[ _Això podria ser un article en si mateix però aquí també hi ha d'anar_ ]

- __Paquets__
- __Aplicació Shiny__
    
## Què falta?

- Clarament comparació amb altres mètodes

# Discussio

- Que fa el metode i "què no"
- Més que un mètode universal -que també- és un mètode que seveix per casos on la CoRnegativa no
- Dit d'altra forma: _Te interès un mètode que classifica o selecciona candidats a xxx però no pot proporcionar un % d’encert?_
    + Si perquè redueix la llista d’elements a analitzar
    + No perquè no tenim mesura de la fiabiitat
    Sempre podem canviar-ho per una major estringencia
- No tenim clar que això sigui un classificador. 
- Convé parlar també dels paràmetres: Hi ha molts paràmetres interrelacionats:
    - Flexible
    - Difícil d’optimitzar

## Limitacions

- Hi ha moltes formes de definir les puntuacions (per cert això mostra que els % han de sumar 100!)
- Hi ha molts més negatius que positius i hi ha moltes formes de ser negatiu (amb scores zero o amb scores negatius)
- Problemes en la comparació amb altres mètodes: 
    - Compte amb la comparació:podem comparar nombre de gens seleccionats, però NO els ben seleccionats!
    - Això lliga amb la problemàtica anterior i amb la següent: Com comparem, amb les dades simulades (on sabriem TRUE/FALSE) o amb les dades reals
    - Podem fer servir l'aplicació a datasets la página de "Pubmeth" (http://www.pubmeth.org/) on tens
        + l'opció de buscar listes de gens (http://pubmeth.biobix.be/temp/static/) que se sap que estan metilats, en quin tipus de cancer es metilen epan metilados y en qué tipo de cáncer 
        + l'opció de revisar si el teu gen d'interes està metilado en cáncer i en quin tipus (http://pubmeth.biobix.be/mate/gene_cancer.html).


# Conclusions

_This should state clearly the main conclusions and provide an explanation of the importance and relevance of the study to the field._

# Methods. 

Això és el que es diu a BMC Bioinformatics de la secció dels mètodes:
<it>
The methods section should include:
1. the aim, design and setting of the study
2. the characteristics of participants or description of materials
3. a clear description of all processes, interventions and comparisons. Generic names should generally be used. When proprietary brands are used in research, include the brand names in parentheses
4. the type of statistical analysis used, including a power calculation if appropriate
9. List of Abbreviations
</it>

En el nostre cas en el que _el resultat és un mètode_ no estic segur de si serà el mateix.

